#!/usr/bin/env python3
"""Validate a command source against a versioned embodiment manifest and build a hashed replay package.

CPU only, no Isaac. The package (manifest copy, converted sequence, controller, hashes, probe config)
is what ``tools/probes/command_replay.py`` executes inside the isolated simulator through the existing
admitted launcher; this tool never launches anything. ``--validate-only`` reports conversion results and
refusals without writing a package.

Source spec (JSON): {"source": {source_id, kind, provenance, ...}, "hand_contracts": {side: {axis_order,
open_value, closed_value, saturation_policy?}}, "rows": [{t_s, body_q_rad|null, hands: {side: [6]|null}}],
"maximum_step_s"?: float, "observed"?: [...]}. ``--synthetic hand-open-close`` generates an explicitly
synthetic contract-test sequence instead of reading a spec.
"""
import argparse
import hashlib
import json
import math
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / 'isaac' / 'twin'))
from inspire.embodiment import ContractError, EmbodimentManifest, ReplaySequence, dependency_values_from_urdf  # noqa: E402

COLLISION_COOKING = 'right=ftp_palm_yz_slabs_v2;left=ftp_left_palm_yz_slabs_v1;contact_offset_m=0.0012860533315688372;rest_offset_m=0'   # the probe's declared provisional colliders

SYNTHETIC_CONTRACT = {'axis_order': ['index', 'middle', 'ring', 'little', 'thumb_bend', 'thumb_rotation'], 'open_value': 0.0, 'closed_value': 1.0, 'saturation_policy': 'reject'}


def synthetic_hand_open_close(home, *, rate_hz=30.0, duration_s=3.0, elbow_amplitude_rad=0.15):
    """Right hand closes (0->1 over 1 s), holds, opens; right elbow sways +-amplitude about home. Explicitly synthetic."""
    rows = []
    n = int(round(duration_s * rate_hz))
    for i in range(n + 1):
        t = i / rate_hz
        closure = min(t, 1.0) if t < 1.5 else max(0.0, 1.0 - (t - 1.5))
        thumb_rot = 0.5 * closure
        rows.append({'t_s': round(t, 6), 'body_q_rad': {'right_elbow_joint': home['right_elbow_joint'] + elbow_amplitude_rad * math.sin(2 * math.pi * t / duration_s)},
                     'hands': {'right': [round(closure, 6)] * 5 + [round(thumb_rot, 6)], 'left': None}})
    return {'source': {'source_id': 'synthetic-hand-open-close-v1', 'kind': 'synthetic_test_sequence',
                       'provenance': 'generated by tools/replay_commands.py --synthetic hand-open-close; NOT a recording of any robot; contract test only'},
            'hand_contracts': {'right': SYNTHETIC_CONTRACT}, 'rows': rows, 'maximum_step_s': 0.5}


def sha(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def validate_controller_gains(manifest, controller):
    """Types, finiteness, named joints and declared ranges of the replay controller (first layer; the probe re-checks at runtime)."""
    problems = []
    allow_zero = set(controller.get('allow_zero_stiffness_joints') or [])
    for key, low, high in (('body_kp_nm_rad', 0.0, 5000.0), ('body_kd_nm_s_rad', 0.0, 500.0)):
        block = controller.get(key)
        if not isinstance(block, dict) or set(block) != set(manifest.body_names):
            problems.append('controller.%s must map exactly the 29 body joints' % key); continue
        for n, v in block.items():
            if isinstance(v, bool) or not isinstance(v, (int, float)) or not math.isfinite(v) or v < low or v > high:
                problems.append('controller.%s[%s] = %r is not a finite value in [%s, %s]' % (key, n, v, low, high))
            elif key == 'body_kp_nm_rad' and v == 0.0 and n not in allow_zero:
                problems.append('controller.body_kp_nm_rad[%s] is zero without allow_zero_stiffness_joints declaring it' % n)
    for key, low, high in (('hand_kp_nm_rad', 0.0, 10.0), ('hand_kd_nm_s_rad', 0.0, 1.0)):
        v = controller.get(key)
        if isinstance(v, bool) or not isinstance(v, (int, float)) or not math.isfinite(v) or v < low or v > high or (key == 'hand_kp_nm_rad' and v == 0.0):
            problems.append('controller.%s = %r is not a finite value in (%s, %s]' % (key, v, low, high))
    if not isinstance(controller.get('provenance'), str) or len(controller.get('provenance', '')) < 20:
        problems.append('controller.provenance must describe the gain origin')
    gff = controller.get('gravity_feedforward')
    if gff is not None:
        if not isinstance(gff, dict) or gff.get('enabled') not in (True, False):
            problems.append('controller.gravity_feedforward must be an object with a boolean enabled')
        elif gff['enabled']:
            if gff.get('source') != 'articulation_generalized_gravity_forces_current_configuration' or gff.get('joints') != 'commanded_body_joints' or gff.get('combined_effort_limit') != 'urdf_effort_limit':
                problems.append('controller.gravity_feedforward must declare source=articulation_generalized_gravity_forces_current_configuration, joints=commanded_body_joints, combined_effort_limit=urdf_effort_limit')
            for key, low, high in (('ramp_in_s', 0.0, 5.0), ('scale', 0.0, 1.0)):
                v = gff.get(key, 1.0)
                if isinstance(v, bool) or not isinstance(v, (int, float)) or not math.isfinite(v) or v < low or v > high or (key == 'scale' and v == 0.0):
                    problems.append('controller.gravity_feedforward.%s = %r out of range' % (key, v))
    return problems


def validate(manifest, spec, controller, *, live_dependencies=None, require_verified_hand_semantics=False):
    """Return (sequence, report). Refusals are collected as data, never as a crash."""
    problems = []
    try:
        sequence = ReplaySequence(manifest, spec['rows'], hand_contracts=spec['hand_contracts'], source=spec['source'], maximum_step_s=spec.get('maximum_step_s', 1.0))
    except (ContractError, KeyError, TypeError) as exc:
        return None, {'status': 'REJECTED', 'problems': [str(exc)]}
    for k in ('body_home_rad', 'body_kp_nm_rad', 'body_kd_nm_s_rad', 'hand_kp_nm_rad', 'hand_kd_nm_s_rad', 'provenance'):
        if k not in controller:
            problems.append('controller.%s missing' % k)
    if not problems:
        for k in ('body_home_rad', 'body_kp_nm_rad', 'body_kd_nm_s_rad'):
            if set(controller[k]) != set(manifest.body_names):
                problems.append('controller.%s must cover exactly the 29 body joints' % k)
        for n in manifest.body_names:
            lo, hi = manifest.body_limit(n)
            v = controller['body_home_rad'].get(n)
            if not isinstance(v, (int, float)) or not math.isfinite(v) or not lo <= v <= hi:
                problems.append('controller home %s outside limits' % n)
    if controller.get('manifest_sha256') not in (None, manifest.sha256):
        problems.append('controller was declared for a different manifest (%s)' % controller.get('manifest_sha256'))
    problems += validate_controller_gains(manifest, controller)
    if require_verified_hand_semantics:
        for side, contract in spec['hand_contracts'].items():
            sem = contract.get('axis_semantics')
            if not isinstance(sem, dict):
                problems.append('%s hand contract declares no axis_semantics; a qualified route needs VERIFIED direction/order/scale per axis' % side); continue
            for axis in contract['axis_order']:
                st = sem.get(axis, {})
                bad = [k for k in ('direction', 'order', 'scale') if st.get(k) != 'VERIFIED']
                if bad:
                    problems.append('%s.%s semantics not VERIFIED for %s (%s)' % (side, axis, ', '.join(bad), json.dumps(st)))
    validity = None
    if live_dependencies is not None:
        if live_dependencies.get('urdf_sha256') != manifest.data['source_asset']['urdf_sha256']:
            problems.append('incompatible profile: the mounted asset hash differs from the manifest source asset')
        validity = manifest.check_validity(live_dependencies)
        bad_transforms = {k: v for k, v in validity['transforms'].items() if v['status'] != 'VALID'}
        if bad_transforms:
            problems.append('transform validity failed: %s' % json.dumps(bad_transforms))
        replay_claim = validity['claims'].get('command_replay_integration')
        if replay_claim and replay_claim['active_compatibility'] == 'STALE':
            problems.append('command_replay_integration binding is STALE: %s' % json.dumps(replay_claim['mismatched']))
    report = {'status': 'REJECTED' if problems else 'VALID', 'problems': problems, 'summary': sequence.summary(), 'qualification_validity': validity}
    return (None if problems else sequence), report


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--manifest', type=Path, required=True, help='embodiment manifest JSON (isaac/twin/inspire/embodiments/*.json)')
    ap.add_argument('--controller', type=Path, required=True, help='controller JSON: body_home_rad/body_kp_nm_rad/body_kd_nm_s_rad by name, hand_kp_nm_rad, hand_kd_nm_s_rad, provenance')
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument('--source-spec', type=Path, help='source spec JSON (rows + hand contracts + provenance)')
    g.add_argument('--synthetic', choices=['hand-open-close'], help='generate an explicitly synthetic contract-test sequence')
    ap.add_argument('--out', type=Path, help='package directory to create (must not exist); omitted with --validate-only')
    ap.add_argument('--validate-only', action='store_true', help='report conversion/refusals and exit without writing a package')
    ap.add_argument('--mount-name', default='replay-package', help='private input name the launcher mounts at /workspace/<name>')
    ap.add_argument('--frame-every', type=int, default=8); ap.add_argument('--lead-in-s', type=float, default=0.5); ap.add_argument('--maximum-steps', type=int, default=4000)
    ap.add_argument('--source-urdf', type=Path, help='the donor URDF that will be mounted; its live dependency values are checked against the manifest bindings before admission')
    ap.add_argument('--support', default='FIXED_PELVIS'); ap.add_argument('--controller-descriptor', default='implicit_biased_drive_v1 replay controller (package-hashed gains)')
    ap.add_argument('--require-verified-hand-semantics', action='store_true', help='qualified route: refuse hand axes whose direction/order/scale are not VERIFIED in the source contract')
    ap.add_argument('--scene', type=Path, help='authored scene JSON (table/object/destination) embedded into the probe config; the object is a free rigid body')
    ap.add_argument('--hand-init', default='urdf_open', choices=['urdf_open', 'first_row_if_nearly_open'], help='probe hand initialisation: at the URDF open pose with a ramp (default) or at the first row when it is an observed nearly-open hand (<= 0.15 rad on every joint)')
    ap.add_argument('--execution-label', default='COMMAND REPLAY', choices=['COMMAND REPLAY', 'SCRIPTED BASELINE', 'MODEL ACTION REPLAY', 'CLOSED LOOP', 'FAILED DIAGNOSTIC', 'DIAGNOSTIC'])
    a = ap.parse_args(argv)
    manifest = EmbodimentManifest.load(a.manifest)
    controller = json.loads(a.controller.read_text())
    spec = synthetic_hand_open_close(controller['body_home_rad']) if a.synthetic else json.loads(a.source_spec.read_text())
    live = None
    if a.source_urdf is not None:
        live = dict(dependency_values_from_urdf(a.source_urdf, collision_cooking=COLLISION_COOKING), support=a.support, controller=a.controller_descriptor)
    sequence, report = validate(manifest, spec, controller, live_dependencies=live, require_verified_hand_semantics=a.require_verified_hand_semantics)
    report.update(manifest_id=manifest.data['manifest_id'], manifest_sha256=manifest.sha256, validated_utc=datetime.now(timezone.utc).isoformat())
    if a.validate_only or sequence is None:
        print(json.dumps(report, indent=1))
        return 0 if report['status'] == 'VALID' else 2
    if a.out is None:
        ap.error('--out is required to write a package')
    if a.out.exists():
        ap.error('package directory exists; packages are never overwritten')
    a.out.mkdir(parents=True)
    shutil.copy2(a.manifest, a.out / 'manifest.json')
    (a.out / 'sequence.json').write_text(json.dumps({k: spec[k] for k in ('source', 'hand_contracts', 'rows') } | ({'maximum_step_s': spec['maximum_step_s']} if 'maximum_step_s' in spec else {}), indent=1) + '\n')
    (a.out / 'controller.json').write_text(json.dumps(controller, indent=1) + '\n')
    if spec.get('observed'):
        (a.out / 'observed.json').write_text(json.dumps(spec['observed'], indent=1) + '\n')
    files = {n: sha(a.out / n) for n in ('manifest.json', 'sequence.json', 'controller.json')}
    package = {'schema_version': 1, 'kind': 'command_replay_package', 'created_utc': report['validated_utc'], 'manifest_id': manifest.data['manifest_id'],
               'manifest_sha256': manifest.sha256, 'contract_sha256': sequence.contract_sha256, 'files': files, 'validation': report,
               'observed_file': 'observed.json' if spec.get('observed') else None}
    (a.out / 'package.json').write_text(json.dumps(package, indent=1) + '\n')
    probe_config = {'package': '/workspace/' + a.mount_name, 'frame_every': a.frame_every, 'lead_in_s': a.lead_in_s, 'maximum_steps': a.maximum_steps,
                    'package_sha256': sha(a.out / 'package.json'), 'execution_label': a.execution_label, 'hand_init': a.hand_init}
    if a.scene is not None:
        scene = json.loads(a.scene.read_text()); probe_config['scene'] = scene; probe_config['scene_sha256'] = sha(a.scene)
    (a.out / 'probe-config.json').write_text(json.dumps(probe_config, indent=1) + '\n')
    print(json.dumps({'package': str(a.out), 'package_sha256': probe_config['package_sha256'], 'contract_sha256': sequence.contract_sha256, 'summary': report['summary']}, indent=1))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
