#!/usr/bin/env python3
"""Validate a command source against a versioned embodiment manifest and build a hashed replay package.

CPU only, no Isaac. The package (manifest copy, converted sequence, controller, hashes, probe config)
is what ``tools/probes/command_replay.py`` executes inside the isolated simulator through the existing
admitted launcher; this tool never launches anything. ``--validate-only`` reports conversion results and
refusals without writing a package.

Source spec (JSON): {"source": {source_id, kind, provenance, ...}, "hand_contracts": {side: {axis_order,
open_value, closed_value, saturation_policy?}}, "rows": [{t_s, body_q_rad|null, hands: {side: [6]|null}}],
"maximum_step_s"?: float, "observed"?: [...]}. ``--synthetic hand-open-close`` generates an explicitly
synthetic contract-test sequence instead of reading a spec.
"""
import argparse
import hashlib
import json
import math
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / 'isaac' / 'twin'))
from inspire.embodiment import ContractError, EmbodimentManifest, ReplaySequence  # noqa: E402

SYNTHETIC_CONTRACT = {'axis_order': ['index', 'middle', 'ring', 'little', 'thumb_bend', 'thumb_rotation'], 'open_value': 0.0, 'closed_value': 1.0, 'saturation_policy': 'reject'}


def synthetic_hand_open_close(home, *, rate_hz=30.0, duration_s=3.0, elbow_amplitude_rad=0.15):
    """Right hand closes (0->1 over 1 s), holds, opens; right elbow sways +-amplitude about home. Explicitly synthetic."""
    rows = []
    n = int(round(duration_s * rate_hz))
    for i in range(n + 1):
        t = i / rate_hz
        closure = min(t, 1.0) if t < 1.5 else max(0.0, 1.0 - (t - 1.5))
        thumb_rot = 0.5 * closure
        rows.append({'t_s': round(t, 6), 'body_q_rad': {'right_elbow_joint': home['right_elbow_joint'] + elbow_amplitude_rad * math.sin(2 * math.pi * t / duration_s)},
                     'hands': {'right': [round(closure, 6)] * 5 + [round(thumb_rot, 6)], 'left': None}})
    return {'source': {'source_id': 'synthetic-hand-open-close-v1', 'kind': 'synthetic_test_sequence',
                       'provenance': 'generated by tools/replay_commands.py --synthetic hand-open-close; NOT a recording of any robot; contract test only'},
            'hand_contracts': {'right': SYNTHETIC_CONTRACT}, 'rows': rows, 'maximum_step_s': 0.5}


def sha(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def validate(manifest, spec, controller):
    """Return (sequence, report). Refusals are collected as data, never as a crash."""
    problems = []
    try:
        sequence = ReplaySequence(manifest, spec['rows'], hand_contracts=spec['hand_contracts'], source=spec['source'], maximum_step_s=spec.get('maximum_step_s', 1.0))
    except (ContractError, KeyError, TypeError) as exc:
        return None, {'status': 'REJECTED', 'problems': [str(exc)]}
    for k in ('body_home_rad', 'body_kp_nm_rad', 'body_kd_nm_s_rad', 'hand_kp_nm_rad', 'hand_kd_nm_s_rad', 'provenance'):
        if k not in controller:
            problems.append('controller.%s missing' % k)
    if not problems:
        for k in ('body_home_rad', 'body_kp_nm_rad', 'body_kd_nm_s_rad'):
            if set(controller[k]) != set(manifest.body_names):
                problems.append('controller.%s must cover exactly the 29 body joints' % k)
        for n in manifest.body_names:
            lo, hi = manifest.body_limit(n)
            v = controller['body_home_rad'].get(n)
            if not isinstance(v, (int, float)) or not math.isfinite(v) or not lo <= v <= hi:
                problems.append('controller home %s outside limits' % n)
    if controller.get('manifest_sha256') not in (None, manifest.sha256):
        problems.append('controller was declared for a different manifest (%s)' % controller.get('manifest_sha256'))
    report = {'status': 'REJECTED' if problems else 'VALID', 'problems': problems, 'summary': sequence.summary()}
    return (None if problems else sequence), report


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--manifest', type=Path, required=True, help='embodiment manifest JSON (isaac/twin/inspire/embodiments/*.json)')
    ap.add_argument('--controller', type=Path, required=True, help='controller JSON: body_home_rad/body_kp_nm_rad/body_kd_nm_s_rad by name, hand_kp_nm_rad, hand_kd_nm_s_rad, provenance')
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument('--source-spec', type=Path, help='source spec JSON (rows + hand contracts + provenance)')
    g.add_argument('--synthetic', choices=['hand-open-close'], help='generate an explicitly synthetic contract-test sequence')
    ap.add_argument('--out', type=Path, help='package directory to create (must not exist); omitted with --validate-only')
    ap.add_argument('--validate-only', action='store_true', help='report conversion/refusals and exit without writing a package')
    ap.add_argument('--mount-name', default='replay-package', help='private input name the launcher mounts at /workspace/<name>')
    ap.add_argument('--frame-every', type=int, default=8); ap.add_argument('--lead-in-s', type=float, default=0.5); ap.add_argument('--maximum-steps', type=int, default=4000)
    a = ap.parse_args(argv)
    manifest = EmbodimentManifest.load(a.manifest)
    controller = json.loads(a.controller.read_text())
    spec = synthetic_hand_open_close(controller['body_home_rad']) if a.synthetic else json.loads(a.source_spec.read_text())
    sequence, report = validate(manifest, spec, controller)
    report.update(manifest_id=manifest.data['manifest_id'], manifest_sha256=manifest.sha256, validated_utc=datetime.now(timezone.utc).isoformat())
    if a.validate_only or sequence is None:
        print(json.dumps(report, indent=1))
        return 0 if report['status'] == 'VALID' else 2
    if a.out is None:
        ap.error('--out is required to write a package')
    if a.out.exists():
        ap.error('package directory exists; packages are never overwritten')
    a.out.mkdir(parents=True)
    shutil.copy2(a.manifest, a.out / 'manifest.json')
    (a.out / 'sequence.json').write_text(json.dumps({k: spec[k] for k in ('source', 'hand_contracts', 'rows') } | ({'maximum_step_s': spec['maximum_step_s']} if 'maximum_step_s' in spec else {}), indent=1) + '\n')
    (a.out / 'controller.json').write_text(json.dumps(controller, indent=1) + '\n')
    if spec.get('observed'):
        (a.out / 'observed.json').write_text(json.dumps(spec['observed'], indent=1) + '\n')
    files = {n: sha(a.out / n) for n in ('manifest.json', 'sequence.json', 'controller.json')}
    package = {'schema_version': 1, 'kind': 'command_replay_package', 'created_utc': report['validated_utc'], 'manifest_id': manifest.data['manifest_id'],
               'manifest_sha256': manifest.sha256, 'contract_sha256': sequence.contract_sha256, 'files': files, 'validation': report,
               'observed_file': 'observed.json' if spec.get('observed') else None}
    (a.out / 'package.json').write_text(json.dumps(package, indent=1) + '\n')
    probe_config = {'package': '/workspace/' + a.mount_name, 'frame_every': a.frame_every, 'lead_in_s': a.lead_in_s, 'maximum_steps': a.maximum_steps,
                    'package_sha256': sha(a.out / 'package.json')}
    (a.out / 'probe-config.json').write_text(json.dumps(probe_config, indent=1) + '\n')
    print(json.dumps({'package': str(a.out), 'package_sha256': probe_config['package_sha256'], 'contract_sha256': sequence.contract_sha256, 'summary': report['summary']}, indent=1))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
